---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-quarkus-app
spec:
  params:
    - name: contextDir
      description: the context dir within source
      default: .
    - name: mavenMirrorUrl
      description: the maven mirrror url
      default: https://repo.maven.apache.org/maven2/
    - name: buildId
      description: ID for the build
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: build
      image: docker.io/maven:3.6.3-openjdk-11-slim
      workingDir: "/workspace/source/$(inputs.params.contextDir)"
      command:
        - mvn
      args:
        - -Dquarkus.container-image.push=true
        - -Dmaven.repo.local=/m2-cache
        - -Dsonar.host.url=http://sonarqube:9000
        - "-Dquarkus.container-image.additional-tags=$(inputs.params.buildId),latest"
        - clean
        - package
        - sonar:sonar
      volumeMounts:
        - mountPath: /m2-cache
          name: m2-cache
  volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache

