apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven
spec:
  workspaces:
  - name: maven-repo
  - name: source
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
    - name: CONTEXT_DIR
      description: The context directory within the repository for sources on which
        we want to execute maven goals.
      type: string
      default: .
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(inputs.params.GOALS)"
