{
 "title": "Color Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests  by Color",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (color) (rate(application_io_riju_demo_ColorResource_colorCalls_total[20s]))",
     "legendFormat": "{{color}}"
    }
   ]
  },
  {
   "title": "Requests  by Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (version) (rate(application_io_riju_demo_ColorResource_colorCalls_total[20s]))",
     "legendFormat": "{{color}}"
    }
   ]
  },
  {
   "title": "Number of Pods by Color",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (color) (application_io_riju_demo_ColorResource_colorCalls_total)",
     "legendFormat": "{{ color }}"
    }
   ]
  },
  {
   "title": "Number of Pods by Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (version) (application_io_riju_demo_ColorResource_colorCalls_total)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(application_io_riju_demo_ColorResource_colorCalls_total)"
    }
   ]
  }
 ]
}