scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kubernetes-pod"
    scrape_interval: 5s
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          own_namespace: true
  

    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      - source_labels:
          [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace

      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name

      - source_labels: [__meta_kubernetes_pod_label_serving_knative_dev_service]
        target_label: knative_service

      - source_labels:
          [__meta_kubernetes_pod_label_serving_knative_dev_revision]
        target_label: knative_revision
