apiVersion: v1
kind: Service
metadata:
  labels:
    app: color-service-green
    app.kubernetes.io/component: color-service-green
    app.kubernetes.io/instance: color-service-green
    app.kubernetes.io/name: color-service-green
    app.kubernetes.io/part-of: color-service-green
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: latest
  name: color-service-green
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: color-service-green
    deploymentconfig: color-service-green
  sessionAffinity: None
  type: ClusterIP