apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-quarkus-app-native
spec:
  resources:
  - name: source
    type: git
  params:
  - name: buildId
    type: string
    description: ID of build
  tasks:
  - name: build-quarkus-app-native
    params:
    - name: contextDir
      value: .
    - name: mavenMirrorUrl
      value: https://repo.maven.apache.org/maven2/
    resources:
      inputs:
      - name: source
        resource: source
    taskRef:
      kind: Task
      name: build-quarkus-app-native
    params:
    - name: buildId
      value: "$(params.buildId)"

