apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: "2021-08-02T14:44:14Z"
  generation: 2
  name: build-quarkus-app
  namespace: color-service
  resourceVersion: "314387"
  uid: d47dcdbe-ed87-4a68-b97d-46222e252984
spec:
  params:
  - description: Repository Name
    name: repo-full-name
    type: string
  - description: Service Name
    name: service-name
    type: string
  - description: Revision of Build
    name: revision
    type: string
  - description: Name of image that should be built
    default: >-
      image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.service-name):$(params.revision)
    name: image
    type: string
  - description: Location of the Containerfile or Dockerfile
    default: ./color-service/src/main/docker/Dockerfile.jvm
    name: dockerfile
    type: string
  resources:
  - name: source
    type: git
  tasks:
  - name: build-quarkus-app
    resources:
      inputs:
      - name: source
        resource: source
    taskRef:
      kind: Task
      name: build-quarkus-app
  - name: build-quarkus-container-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.image)
    - name: DOCKERFILE
      value: $(params.dockerfile)
    runAfter:
    - build-quarkus-app
  workspaces:
    - name: workspace
