apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: color-service
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: color-service
    template:
      ref: color-service