apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkus-app
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: quarkus-app
    template:
      name: build-quarkus-app
