apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerTemplate 
metadata:
  name: color-service
spec:
  params: 
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git revision
    default: master
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  resourcetemplates: 
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: color-service-$(params.git-repo-name)-$(uid)
    spec:
      pipelineRef:
        name: color-service
      params:
      - name: image-name
        value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.service-name)
      - name: context-dir
        value: .
      - name: service-name
        value: color-service
      - name: git-repo-url
        value: $(tt.params.git-repo-url)
      - name: git-repo-revision
        value: $(tt.params.git-revision)
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
      - name: source
        volumeClaimTemplate:
          metadata:
            name: color-service-
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp2
            volumeMode: Filesystem
      - name: maven-repo
        persistentVolumeClaim:
          claimName: maven-repo

